#!/usr/bin/env bash
# builds a pr body (to stdout) from a finding's json.
# usage: pr-build-body.sh <finding_id>
set -euo pipefail
# shellcheck disable=SC1091
source "${BASH_SOURCE%/*}/lib/state.sh"

id="${1:-}"
[ -n "$id" ] || die "usage: $0 <finding_id>"
f="$(finding_file "$id")"
[ -f "$f" ] || die "no such finding: $id"

jq -r '
  # strip backticks from LLM-controlled fields so they cannot break our
  # inline-code spans or fenced blocks when pasted into GitHub markdown.
  def clean: (. // "") | tostring | gsub("`"; "'"'"'");
  def cleanblock: (. // "") | tostring | gsub("```"; "\u2018\u2018\u2018");
  def section(h; b): if (b | length) > 0 then "## \(h)\n\n\(b)\n" else "" end;
  def codefence(s): if (s | length) > 0 then "```\n\(s)\n```" else "" end;
  "**Auto-audit finding: \(.id | clean)** — severity: `\(.severity | clean)`, category: `\(.category | clean)`\n"
  + "\n### \(.title | clean)\n"
  + "\nLocation: `\(.file | clean):\(.line)`\n"
  + section("Description"; .description | clean)
  + section("Code (before)"; codefence(.code_snippet | cleanblock))
  + section("Triage"; (.triage // {} | .reasoning // "" | clean))
  + section("Proof of concept"; (.poc // {} | .content // "" | cleanblock))
  + section("Fix summary"; (.fix // {} | .diff_summary // "" | cleanblock))
  + section("Independent review"; (.review // {} | .reasoning // "" | clean))
  + "\n---\n"
  + "_Generated by auto-audit plugin. This PR is produced and reviewed by an autonomous agent; please give it a human look before trusting it._\n"
' "$f"
