#!/usr/bin/env bash
# builds a pr body (to stdout) from a finding's json.
# usage: pr-build-body.sh <finding_id>
#
# Deliberately excludes .triage.reasoning and .fix.diff_summary: the
# independent reviewer reads this PR body (directly or indirectly), and the
# whole point of the independent-review checkpoint is that the reviewer does
# not see the fixer's or triager's reasoning. Those fields remain in the
# finding JSON for human inspection via /auto-audit:status, but they never
# travel with the PR.
set -euo pipefail
# shellcheck disable=SC1091
source "${BASH_SOURCE%/*}/lib/state.sh"

id="${1:-}"
[ -n "$id" ] || die "usage: $0 <finding_id>"
f="$(finding_file "$id")"
[ -f "$f" ] || die "no such finding: $id"

jq -r '
  # strip backticks from LLM-controlled fields so they cannot break our
  # inline-code spans or fenced blocks when pasted into GitHub markdown.
  def clean: (. // "") | tostring | gsub("`"; "'"'"'");
  def cleanblock: (. // "") | tostring | gsub("```"; "\u2018\u2018\u2018");
  def section(h; b): if (b | length) > 0 then "## \(h)\n\n\(b)\n" else "" end;
  def codefence(s): if (s | length) > 0 then "```\n\(s)\n```" else "" end;
  "**Auto-audit finding: \(.id | clean)** — severity: `\(.severity | clean)`, category: `\(.category | clean)`\n"
  + "\n### \(.title | clean)\n"
  + "\nLocation: `\(.file | clean):\(.line | clean)`\n"
  + section("Description"; .description | clean)
  + section("Code (before)"; codefence(.code_snippet | cleanblock))
  + "\n---\n"
  + "_Generated by the auto-audit plugin. The diff in this PR was written by one agent and will be reviewed by a separate, independent agent that has no visibility into the fixer''s reasoning. Please still give it a human look before merging._\n"
' "$f"
